//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class musteri
    {
        public int musteri_Id { get; set; }
        [Required(ErrorMessage ="Boþ Býrakmazsýnýz")]
        public string musteri_adi { get; set; }
        [Required(ErrorMessage = "Boþ Býrakmazsýnýz")]
        public string musteri_adres { get; set; }
        [Required(ErrorMessage = "Boþ Býrakmazsýnýz")]
        public string musteri_kul { get; set; }
        [Required(ErrorMessage = "Boþ Býrakmazsýnýz")]
        public string musteri_sifre { get; set; }
    }
}
