//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resimler
    {
        public int Resim_Id { get; set; }
        public string Resim_Ad { get; set; }
        public Nullable<int> Musteri_Id { get; set; }
    }
}
